// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using InventorySystem.Infrastructure.Database;

#nullable disable

namespace InventorySystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250201120000_InitialIdentity")]
    partial class InitialIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("InventorySystem.Domain.Identity.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");
                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");
                    b.Property<string>("NombreParaMostrar")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");
                    b.Property<string>("HashContraseña")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");
                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");
                    b.Property<bool>("RequiereCambioContraseña")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);
                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);
                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("TEXT");
                    b.Property<DateTimeOffset?>("UltimoAcceso")
                        .HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("NombreUsuario")
                        .IsUnique();
                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("InventorySystem.Domain.Identity.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");
                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("Nombre")
                        .IsUnique();
                    b.ToTable("Roles");
                });

            modelBuilder.Entity("InventorySystem.Domain.Identity.UsuarioRol", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");
                    b.Property<int>("RolId")
                        .HasColumnType("INTEGER");
                    b.HasKey("UsuarioId", "RolId");
                    b.HasIndex("RolId");
                    b.ToTable("UsuarioRoles");
                });

            modelBuilder.Entity("InventorySystem.Domain.Identity.UsuarioRol", b =>
                {
                    b.HasOne("InventorySystem.Domain.Identity.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("InventorySystem.Domain.Identity.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
