// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ContractSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ContractSystem.Infrastructure.Database.ApplicationDbContext))]
    [Migration("20260323110000_AddLicencias")]
    public partial class AddLicencias : Migration
    {
    }
}
