// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ContractSystem.Infrastructure.Database;

#nullable disable

namespace ContractSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260214160000_AddNomUnidadesMedida")]
    partial class AddNomUnidadesMedida
    {
    }
}
