// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ContractSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ContractSystem.Infrastructure.Database.ApplicationDbContext))]
    [Migration("20260315200000_RemoveNumeroUniqueConstraint")]
    public partial class RemoveNumeroUniqueConstraint : Migration
    {
    }
}
