// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ContractSystem.Infrastructure.Database;

#nullable disable

namespace ContractSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("ContractSystem.Domain.Business.BusinessInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");
                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");
                    b.Property<byte[]>("Logo")
                        .HasColumnType("BLOB");
                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");
                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");
                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");
                    b.Property<string>("Eslogan")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");
                    b.Property<string>("NombreDueno")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.ToTable("BusinessInfos");
                });

            modelBuilder.Entity("ContractSystem.Domain.Identity.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");
                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");
                    b.Property<string>("NombreParaMostrar")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");
                    b.Property<string>("HashContraseña")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");
                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");
                    b.Property<bool>("RequiereCambioContraseña")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);
                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);
                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("TEXT");
                    b.Property<DateTimeOffset?>("UltimoAcceso")
                        .HasColumnType("TEXT");
                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");
                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");
                    b.Property<byte[]>("FotoPerfil")
                        .HasMaxLength(524288)
                        .HasColumnType("BLOB");
                    b.HasKey("Id");
                    b.HasIndex("NombreUsuario")
                        .IsUnique();
                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ContractSystem.Domain.Nomencladores.UnidadMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");
                    b.Property<string>("NombreCorto")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");
                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");
                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("NombreCorto")
                        .IsUnique();
                    b.ToTable("nom_UnidadesMedida");
                });

            modelBuilder.Entity("ContractSystem.Domain.Identity.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");
                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");
                    b.Property<string>("Descripcion")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("Nombre")
                        .IsUnique();
                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("ContractSystem.Domain.Identity.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");
                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("Nombre")
                        .IsUnique();
                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ContractSystem.Domain.Identity.RolPermiso", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("INTEGER");
                    b.Property<int>("PermisoId")
                        .HasColumnType("INTEGER");
                    b.HasKey("RolId", "PermisoId");
                    b.HasIndex("PermisoId");
                    b.ToTable("RolPermisos");
                });

            modelBuilder.Entity("ContractSystem.Domain.Identity.UsuarioRol", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");
                    b.Property<int>("RolId")
                        .HasColumnType("INTEGER");
                    b.HasKey("UsuarioId", "RolId");
                    b.HasIndex("RolId");
                    b.ToTable("UsuarioRoles");
                });

            modelBuilder.Entity("ContractSystem.Domain.Identity.RolPermiso", b =>
                {
                    b.HasOne("ContractSystem.Domain.Identity.Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("ContractSystem.Domain.Identity.Rol", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContractSystem.Domain.Identity.UsuarioRol", b =>
                {
                    b.HasOne("ContractSystem.Domain.Identity.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("ContractSystem.Domain.Identity.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
